apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: clone-repo
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: main
    - name: subdir
      type: string
      default: app
  results:
    - name: repo-dir
      description: Répertoire où le repo a été cloné
    - name: commit-sha
      description: SHA du commit cloné
  workspaces:
    - name: source
  steps:
    - name: clone
      image: alpine/git:2.45.2
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -eu
        git clone --depth 1 -b "$(params.revision)" "$(params.repo-url)" "$(params.subdir)"
        printf "%s" "$(params.subdir)" > "$(results.repo-dir.path)"
        (cd "$(params.subdir)" && git rev-parse HEAD) > "$(results.commit-sha.path)"
