apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: pylint
spec:
  params:
    - name: repo-dir
      type: string
      default: app
    - name: venv-path
      type: string
      default: .venv
  results:
    - name: lint-status              
      description: "passed ou failed"
  workspaces:
    - name: source
  steps:
    - name: pylint
      image: python:3.12-slim
      workingDir: $(workspaces.source.path)/$(params.repo-dir)
      script: |
        #!/usr/bin/env sh
        set -eu
        VENV="$(params.venv-path)"
        "$VENV/bin/pip" install --no-cache-dir pylint
        # Exécute pylint et capture le code retour sans casser la task
        if "$VENV/bin/python" -m pylint .; then
          printf "%s" "passed" > "$(results.lint-status.path)"
          exit 0
        else
          printf "%s" "failed" > "$(results.lint-status.path)"
          exit 1   
        fi
